import { writeFileSync, readFileSync } from 'fs';
import { generateFiles } from 'fumadocs-openapi';

// Download OpenAPI spec from TonAPI
console.log('📥 Downloading OpenAPI spec from https://tonapi.io/v2/openapi.yml...');
const response = await fetch('https://tonapi.io/v2/openapi.yml');
const spec = await response.text();
writeFileSync('./tonapi-openapi.yml', spec);
console.log('✅ OpenAPI spec downloaded successfully!');

// Generate single page from OpenAPI spec
console.log('📄 Generating API documentation page...');
await generateFiles({
  input: './tonapi-openapi.yml',
  output: './docs/tonapi',
  per: 'file',
  name: () => 'rest-api',
  beforeWrite(files) {
    // Add intro content before the generated API page
    const introContent = `
This API is designed to provide users with a simple and streamlined experience, eliminating the complexity of the TON blockchain. For instance, you don't need to worry about supporting all wallet standards, performing verifications, or decoding raw bits and bytes.

## Authorization

All methods are available without authentication, but with a rate limit of 1 request per 4 seconds (0.24 rps).

To authorize your request, you will need a token, which you can obtain from [TonConsole](https://tonconsole.com/). To pass the token in your request, add the Authorization HTTP header with the "Bearer scheme":

\`\`\`bash
curl \\
 -H 'Authorization: Bearer YOUR_TOKEN_HERE' \\
 'https://tonapi.io/v2/blockchain/masterchain-head'
\`\`\`

## Rate Limits

The rate limits for all of your issued tokens are the same and match the plan you have. Learn more about tiers and limits on [TonConsole](https://tonconsole.com/tonapi/pricing).

## Base URLs

- **Mainnet**: \`https://tonapi.io\`
- **Testnet**: \`https://testnet.tonapi.io\`

---

`;

    // Add intro before APIPage component
    for (const file of files) {
      if (file.path.includes('rest-api.mdx')) {
        const lines = file.content.split('\n');
        const commentIndex = lines.findIndex(line => line.includes('This file was generated by Fumadocs'));
        if (commentIndex !== -1) {
          lines.splice(commentIndex + 1, 0, introContent);
          file.content = lines.join('\n');
        }
      }
    }
  },
});
console.log('✅ API documentation page generated!');
